import { Category, Product, Combo } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-super-combos',
    name: 'Super Combos',
    slug: 'combos',
    description: 'Los mejores combos de la ciudad: más ahorro, máxima frescura.',
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'cat-verdulería',
    name: 'Verdulería',
    slug: 'verduleria',
    description: 'Verduras seleccionadas día a día del campo a tu cocina.',
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'cat-frutería',
    name: 'Frutería',
    slug: 'fruteria',
    description: 'Frutas de estación dulces, jugosas y listas para disfrutar.',
    image_url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'cat-carnes',
    name: 'Carnes',
    slug: 'carnes',
    description: 'Cortes premium de primera calidad para tu mesa y asador.',
    image_url: 'https://images.unsplash.com/photo-1603048588665-791ca8aea617?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'cat-pollería',
    name: 'Pollería',
    slug: 'polleria',
    description: 'Pollo fresco y tiernizado con los mejores cortes limpios.',
    image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    id: 'cat-fiambrería',
    name: 'Fiambrería',
    slug: 'fiambreria',
    description: 'Quesos de campo, jamones y fiambres feteados en el momento.',
    image_url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  // VERDULERÍA
  {
    id: 'prod-papa',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Papa Negra Seleccionada',
    slug: 'papa-negra-seleccionada',
    description: 'Papa de campo ideal para freír, hervir o hacer puré cremoso.',
    price: 950,
    previous_price: 1200,
    stock: 120,
    image_url: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-tomate',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Tomate Redondo Especial',
    slug: 'tomate-redondo-especial',
    description: 'Tomate firme, maduro y con gran aroma para ensaladas y salsas.',
    price: 1450,
    previous_price: 1800,
    stock: 85,
    image_url: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-cebolla',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Cebolla Dorada',
    slug: 'cebolla-dorada',
    description: 'Cebollas secas de tamaño mediano-grande, sin brotes.',
    price: 890,
    previous_price: null,
    stock: 95,
    image_url: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-zanahoria',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Zanahoria Dulce',
    slug: 'zanahoria-dulce',
    description: 'Zanahorias frescas de raíz crujiente y color naranja vivo.',
    price: 900,
    previous_price: 1100,
    stock: 60,
    image_url: 'https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-lechuga',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Lechuga Criolla / Mantecosa',
    slug: 'lechuga-criolla',
    description: 'Hojas frescas, crocantes y limpiadas cuidadosamente.',
    price: 1100,
    previous_price: 1400,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-morron',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Morrón Rojo Grueso',
    slug: 'morron-rojo-grueso',
    description: 'Pimiento morrón carnoso, ideal para asar o rellenar.',
    price: 2400,
    previous_price: 2900,
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-ajo',
    category_id: 'cat-verdulería',
    category_slug: 'verduleria',
    category_name: 'Verdulería',
    name: 'Ajo Morado (Cabeza)',
    slug: 'ajo-morado',
    description: 'Cabezas de ajo con dientes grandes, fragantes y sabrosos.',
    price: 450,
    previous_price: null,
    stock: 150,
    image_url: 'https://images.unsplash.com/photo-1540148426945-6cf22a6b2383?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'unidad',
  },

  // FRUTERÍA
  {
    id: 'prod-banana',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Banana Premium de Ecuador',
    slug: 'banana-premium-ecuador',
    description: 'Bananas en punto justo de maduración, dulces y energéticas.',
    price: 1650,
    previous_price: 1950,
    stock: 110,
    image_url: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-manzana',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Manzana Roja Deliciosa',
    slug: 'manzana-roja-deliciosa',
    description: 'Crocante, dulce y brillante del Valle de Río Negro.',
    price: 1550,
    previous_price: null,
    stock: 75,
    image_url: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-naranja',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Naranja de Jugo Dulce',
    slug: 'naranja-jugo-dulce',
    description: 'Naranjas de cáscara fina con alto contenido de jugo natural.',
    price: 1200,
    previous_price: 1500,
    stock: 90,
    image_url: 'https://images.unsplash.com/photo-1582979512210-99b6a53386f9?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-mandarina',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Mandarina Criolla',
    slug: 'mandarina-criolla',
    description: 'Fácil de pelar, sin semillas, perfume inconfundible.',
    price: 1350,
    previous_price: null,
    stock: 65,
    image_url: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-pera',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Pera Williams Jugosa',
    slug: 'pera-williams-jugosa',
    description: 'Pera suave, de pulpa dulce que se deshace en la boca.',
    price: 1400,
    previous_price: null,
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-uva',
    category_id: 'cat-frutería',
    category_slug: 'fruteria',
    category_name: 'Frutería',
    name: 'Uva Red Globe / Moscatel',
    slug: 'uva-red-globe',
    description: 'Racimos seleccionados con grano grande y sabor dulce.',
    price: 2600,
    previous_price: 3100,
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },

  // CARNES
  {
    id: 'prod-asado',
    category_id: 'cat-carnes',
    category_slug: 'carnes',
    category_name: 'Carnes',
    name: 'Asado de Tira Especial',
    slug: 'asado-de-tira-especial',
    description: 'Corte clásico con el marmoleo exacto para la mejor parrillada.',
    price: 7800,
    previous_price: 8900,
    stock: 45,
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-vacio',
    category_id: 'cat-carnes',
    category_slug: 'carnes',
    category_name: 'Carnes',
    name: 'Vacío Tierno',
    slug: 'vacio-tierno',
    description: 'Corte magro y jugoso, ideal para asador lento o al horno.',
    price: 8200,
    previous_price: 9400,
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-carne-picada',
    category_id: 'cat-carnes',
    category_slug: 'carnes',
    category_name: 'Carnes',
    name: 'Carne Picada Especial',
    slug: 'carne-picada-especial',
    description: 'Molida de cortes magros en el día. Ideal para hamburguesas o empanadas.',
    price: 5400,
    previous_price: 6100,
    stock: 70,
    image_url: 'https://images.unsplash.com/photo-1588168333986-5078d3ae3976?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-bife',
    category_id: 'cat-carnes',
    category_slug: 'carnes',
    category_name: 'Carnes',
    name: 'Bife de Chorizo Premium',
    slug: 'bife-de-chorizo-premium',
    description: 'Bife ancho y tierno cortado grueso para la plancha o carbón.',
    price: 8600,
    previous_price: 9900,
    stock: 25,
    image_url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-tapa-asado',
    category_id: 'cat-carnes',
    category_slug: 'carnes',
    category_name: 'Carnes',
    name: 'Tapa de Asado',
    slug: 'tapa-de-asado',
    description: 'Corte versátil y rendidor, sabroso tanto a las brasas como en guisados.',
    price: 6900,
    previous_price: 7600,
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },

  // POLLERÍA
  {
    id: 'prod-pollo-entero',
    category_id: 'cat-pollería',
    category_slug: 'polleria',
    category_name: 'Pollería',
    name: 'Pollo Fresco Entero',
    slug: 'pollo-fresco-entero',
    description: 'Pollo limpio de granja de 2.2 a 2.5 kg aprox. Piel firme y carne tierna.',
    price: 3200,
    previous_price: 3800,
    stock: 60,
    image_url: 'https://images.unsplash.com/photo-1587593810167-a84920ea0781?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-pechuga',
    category_id: 'cat-pollería',
    category_slug: 'polleria',
    category_name: 'Pollería',
    name: 'Suprema / Pechuga Fileteada',
    slug: 'suprema-pechuga-fileteada',
    description: '100% pulpa magra limpia sin piel ni hueso, lista para milanesas.',
    price: 5900,
    previous_price: 6800,
    stock: 50,
    image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-muslo',
    category_id: 'cat-pollería',
    category_slug: 'polleria',
    category_name: 'Pollería',
    name: 'Muslo Deshuesado',
    slug: 'muslo-deshuesado',
    description: 'Carne súper jugosa para wok, brochetas o arrollados.',
    price: 4900,
    previous_price: null,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },
  {
    id: 'prod-patamuslo',
    category_id: 'cat-pollería',
    category_slug: 'polleria',
    category_name: 'Pollería',
    name: 'Pata y Muslo Fresco',
    slug: 'pata-muslo-fresco',
    description: 'El corte preferido para el horno con papas o la parrilla.',
    price: 3600,
    previous_price: 4200,
    stock: 65,
    image_url: 'https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: true,
    unit: 'kg',
  },
  {
    id: 'prod-alitas',
    category_id: 'cat-pollería',
    category_slug: 'polleria',
    category_name: 'Pollería',
    name: 'Alitas de Pollo Crocantes',
    slug: 'alitas-de-pollo',
    description: 'Alitas limpias ideales para marinar con barbacoa o fritas.',
    price: 2800,
    previous_price: 3200,
    stock: 35,
    image_url: 'https://images.unsplash.com/photo-1527477378378-0e3f019fecff?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'kg',
  },

  // FIAMBRERÍA
  {
    id: 'prod-jamon',
    category_id: 'cat-fiambrería',
    category_slug: 'fiambreria',
    category_name: 'Fiambrería',
    name: 'Jamón Cocido Natural Feteado',
    slug: 'jamon-cocido-natural',
    description: 'Jamón tierno de primera calidad feteado fino en máquina.',
    price: 3100,
    previous_price: 3700,
    stock: 40,
    image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: false,
    unit: '300g',
  },
  {
    id: 'prod-queso',
    category_id: 'cat-fiambrería',
    category_slug: 'fiambreria',
    category_name: 'Fiambrería',
    name: 'Queso Gouda / Dambo de Campo',
    slug: 'queso-gouda-dambo',
    description: 'Queso cremoso y consistente, ideal para sándwiches o picadas.',
    price: 3300,
    previous_price: 3900,
    stock: 55,
    image_url: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: true,
    is_offer: true,
    unit: '300g',
  },
  {
    id: 'prod-salame',
    category_id: 'cat-fiambrería',
    category_slug: 'fiambreria',
    category_name: 'Fiambrería',
    name: 'Salame Picado Fino Tipo Colonia',
    slug: 'salame-picado-fino',
    description: 'Estacionado tradicional con pimienta negra en grano.',
    price: 2600,
    previous_price: 3100,
    stock: 30,
    image_url: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: false,
    unit: 'unidad',
  },
  {
    id: 'prod-mortadela',
    category_id: 'cat-fiambrería',
    category_slug: 'fiambreria',
    category_name: 'Fiambrería',
    name: 'Mortadela con Pistacho Gourmet',
    slug: 'mortadela-con-pistacho',
    description: 'Elaboración clásica italiana con especias naturales y pistacho.',
    price: 2400,
    previous_price: 2900,
    stock: 25,
    image_url: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    active: true,
    featured: false,
    is_offer: true,
    unit: '300g',
  },
];

export const INITIAL_COMBOS: Combo[] = [
  {
    id: 'combo-familiar',
    name: 'SUPER COMBO FAMILIAR',
    description: 'El combo salvador de la semana: abastecimiento completo para cocinar rico y variado para toda la familia.',
    price: 24900,
    previous_price: 31500,
    image_url: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '2 kg Papa Negra',
      '1 kg Tomate Redondo',
      '1 kg Cebolla Dorada',
      '1 kg Zanahorias',
      '1 kg Bananas',
      '1 Pollo Fresco Entero',
      '1 kg Carne Picada Especial',
      '1 Horma Queso Dambo (300g)'
    ],
    items: [
      { product_id: 'prod-papa', quantity: 2, unit: 'kg' },
      { product_id: 'prod-tomate', quantity: 1, unit: 'kg' },
      { product_id: 'prod-cebolla', quantity: 1, unit: 'kg' },
      { product_id: 'prod-pollo-entero', quantity: 1, unit: 'unid' },
      { product_id: 'prod-carne-picada', quantity: 1, unit: 'kg' },
    ]
  },
  {
    id: 'combo-parrillero',
    name: 'SUPER COMBO PARRILLERO',
    description: 'Para encender el fuego y disfrutar el mejor asado criollo entre amigos sin vueltas.',
    price: 33500,
    previous_price: 41000,
    image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '2 kg Asado de Tira Especial',
      '1.5 kg Vacío Tierno',
      '1 kg Patamuslo de Pollo',
      '1 kg Morrón Rojo para asar',
      '1 Cabeza de Ajo Morado',
      '1 Salame Picado Fino'
    ],
    items: [
      { product_id: 'prod-asado', quantity: 2, unit: 'kg' },
      { product_id: 'prod-vacio', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-patamuslo', quantity: 1, unit: 'kg' },
      { product_id: 'prod-morron', quantity: 1, unit: 'kg' },
    ]
  },
  {
    id: 'combo-verduras',
    name: 'SUPER COMBO VERDURAS',
    description: 'Todo el color, fibra y vitaminas frescas del día seleccionadas a mano.',
    price: 8400,
    previous_price: 10900,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '3 kg Papa Seleccionada',
      '1.5 kg Tomate Redondo',
      '1.5 kg Cebolla Dorada',
      '1 kg Zanahoria Dulce',
      '1 Planta Lechuga Mantecosa',
      '1 Morrón Rojo',
      '2 Cabezas Ajo Morado'
    ],
    items: [
      { product_id: 'prod-papa', quantity: 3, unit: 'kg' },
      { product_id: 'prod-tomate', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-cebolla', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-zanahoria', quantity: 1, unit: 'kg' },
    ]
  },
  {
    id: 'combo-frutas',
    name: 'SUPER COMBO FRUTAS',
    description: 'La dosis de energía natural para desayunos, meriendas y jugos frescos.',
    price: 7900,
    previous_price: 10200,
    image_url: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '2 kg Banana Premium Ecuador',
      '1.5 kg Manzana Roja Deliciosa',
      '2 kg Naranja de Jugo Dulce',
      '1 kg Pera Williams',
      '1 kg Mandarina Criolla'
    ],
    items: [
      { product_id: 'prod-banana', quantity: 2, unit: 'kg' },
      { product_id: 'prod-manzana', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-naranja', quantity: 2, unit: 'kg' },
      { product_id: 'prod-pera', quantity: 1, unit: 'kg' },
    ]
  },
  {
    id: 'combo-pollo',
    name: 'SUPER COMBO POLLO',
    description: 'Cortes limpios de pollo para milanesas, horno, guisados y dietas proteicas.',
    price: 17900,
    previous_price: 22400,
    image_url: 'https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: false,
    items_summary: [
      '1 Pollo Fresco Entero (aprox 2.4kg)',
      '1.5 kg Pechuga / Suprema Fileteada',
      '1.5 kg Pata y Muslo',
      '1 kg Alitas Crocantes'
    ],
    items: [
      { product_id: 'prod-pollo-entero', quantity: 1, unit: 'unid' },
      { product_id: 'prod-pechuga', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-patamuslo', quantity: 1.5, unit: 'kg' },
    ]
  },
  {
    id: 'combo-completo',
    name: 'SUPER COMBO COMPLETO',
    description: 'La experiencia definitiva: Verduras, Frutas, Carnes, Pollo y Fiambrería en un solo envío.',
    price: 46900,
    previous_price: 58500,
    image_url: 'https://images.unsplash.com/photo-1506484381205-f7945653044d?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '1 SUPER COMBO VERDURAS completo',
      '1 SUPER COMBO FRUTAS completo',
      '1.5 kg Asado de Tira + 1 kg Carne Picada',
      '1 Pollo Entero Granja',
      '300g Jamón Cocido + 300g Queso Dambo',
      '1 Salame Picado Fino',
      '¡Envío GRATIS prioritario en moto!'
    ],
    items: [
      { product_id: 'prod-asado', quantity: 1.5, unit: 'kg' },
      { product_id: 'prod-carne-picada', quantity: 1, unit: 'kg' },
      { product_id: 'prod-pollo-entero', quantity: 1, unit: 'unid' },
      { product_id: 'prod-jamon', quantity: 1, unit: 'pack' },
      { product_id: 'prod-queso', quantity: 1, unit: 'pack' },
    ]
  },
  {
    id: 'combo-milanesero',
    name: 'SUPER COMBO MILANESERO',
    description: 'Todo listo para preparar las mejores milanesas caseras de carne y pollo con papas para freír.',
    price: 21900,
    previous_price: 27500,
    image_url: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '1.5 kg Peceto / Nalga cortada para milanesas',
      '1.5 kg Suprema de Pollo fileteada',
      '3 kg Papa Negra seleccionada',
      '1 Maple de Huevos de Campo (30 unid)',
      '1 Ramillete de Perejil & Ajo fresco'
    ],
    items: []
  },
  {
    id: 'combo-picada',
    name: 'SUPER COMBO PICADA & AMIGOS',
    description: 'El combo ideal para el previaje, picada del fin de semana o juntadas con fiambres seleccionados.',
    price: 18500,
    previous_price: 23200,
    image_url: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: true,
    items_summary: [
      '500g Jamón Cocido Selección',
      '500g Queso Gouda / Dambo',
      '2 Salames Picado Fino Tipo Colonia',
      '300g Mortadela con Pistacho Gourmet',
      '1 Pote Aceitunas Verdes Rellenas'
    ],
    items: []
  },
  {
    id: 'combo-saludable',
    name: 'SUPER COMBO FIT & SALUDABLE',
    description: 'Bajo en grasas, alto en proteínas y repleto de micronutrientes frescos para tu rendimiento diario.',
    price: 16900,
    previous_price: 21000,
    image_url: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: false,
    items_summary: [
      '2 kg Pechugas de Pollo Desgrasadas',
      '1.5 kg Zanahorias y Tomates',
      '1 kg Manzanas Verdes y Rojas',
      '2 kg Naranjas para jugo natural',
      '2 Plantas Lechuga Mantecosa fresca'
    ],
    items: []
  },
  {
    id: 'combo-express',
    name: 'SUPER COMBO EXPRESS SEMANAL',
    description: 'La solución rápida y económica con lo esencial del día a día para 1 o 2 personas.',
    price: 13900,
    previous_price: 17200,
    image_url: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    active: true,
    featured: false,
    items_summary: [
      '1 kg Asado / Carne a elección',
      '1 kg Suprema de Pollo',
      '2 kg Papas Seleccionadas',
      '1 kg Cebollas y Zanahorias',
      '1 kg Bananas'
    ],
    items: []
  },
];
